USE [master]
GO
/****** Object:  Database [QuanLyCungCapVideo]    Script Date: 05/06/2019 5:36:19 CH ******/
CREATE DATABASE [QuanLyCungCapVideo]
GO
USE [QuanLyCungCapVideo]
GO
/****** Object:  Table [dbo].[DICHVU]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DICHVU](
	[IDDV] [int] IDENTITY(1,1) NOT NULL,
	[TenDV] [nvarchar](50) NULL,
	[GiaTien] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDDV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[QUYEN]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[QUYEN](
	[IDQuyen] [int] IDENTITY(1,1) NOT NULL,
	[Quyen] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDQuyen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[IDTK] [int] IDENTITY(1,1) NOT NULL,
	[TenND] [nvarchar](100) NULL,
	[MatKhau] [varchar](50) NULL,
	[DienThoai] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[IDQuyen] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDTK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[THANHTOAN]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THANHTOAN](
	[IDThanhToan] [int] IDENTITY(1,1) NOT NULL,
	[IDTK] [int] NULL,
	[IDDV] [int] NULL,
	[HTTT] [nvarchar](50) NULL,
	[NgayTT] [datetime] NULL,
	[NgayKT] [datetime] NULL,
	[GiaTien] [decimal](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDThanhToan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[THELOAI]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THELOAI](
	[IDTL] [int] IDENTITY(1,1) NOT NULL,
	[TenTL] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDTL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[VIDEO]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VIDEO](
	[IDVideo] [int] IDENTITY(1,1) NOT NULL,
	[TenVideo] [nvarchar](100) NULL,
	[IDTL] [int] NULL,
	[QuocGia] [nvarchar](50) NULL,
	[ThoiLuong] [varchar](30) NULL,
	[DaoDien] [nvarchar](50) NULL,
	[LuotXem] [int] NULL,
	[LinkVideo] [nvarchar](200) NOT NULL,
	[LinkPoster] [nvarchar](200) NULL,
 CONSTRAINT [VIDEO_pk] PRIMARY KEY CLUSTERED 
(
	[IDVideo] ASC,
	[LinkVideo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[YEUTHICH]    Script Date: 05/06/2019 5:36:20 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[YEUTHICH](
	[IDYT] [int] IDENTITY(1,1) NOT NULL,
	[IDTK] [int] NULL,
	[LinkVideo] [nvarchar](200) NULL,
	[LinkPoster] [nvarchar](200) NULL,
	[IDVideo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDYT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[QUYEN] ON 

INSERT [dbo].[QUYEN] ([IDQuyen], [Quyen]) VALUES (1, N'admin')
INSERT [dbo].[QUYEN] ([IDQuyen], [Quyen]) VALUES (2, N'staff')
SET IDENTITY_INSERT [dbo].[QUYEN] OFF
SET IDENTITY_INSERT [dbo].[TAIKHOAN] ON 

INSERT [dbo].[TAIKHOAN] ([IDTK], [TenND], [MatKhau], [DienThoai], [Email], [IDQuyen]) VALUES (1, N'admin', N'admin', N'555151', N'a@gmail.com', 1)
INSERT [dbo].[TAIKHOAN] ([IDTK], [TenND], [MatKhau], [DienThoai], [Email], [IDQuyen]) VALUES (2, N'staff', N'staff', N'651654646', N'b@gmail.com', 2)
SET IDENTITY_INSERT [dbo].[TAIKHOAN] OFF
SET IDENTITY_INSERT [dbo].[THELOAI] ON 

INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (1, N'Tình Cảm')
INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (2, N'Viễn Tưởng')
INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (3, N'Hành Động')
INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (4, N'Phiêu Lưu')
INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (5, N'Hoạt Hình')
INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (6, N'Hài Kịch')
INSERT [dbo].[THELOAI] ([IDTL], [TenTL]) VALUES (7, N'Âm Nhạc')
SET IDENTITY_INSERT [dbo].[THELOAI] OFF

ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TK_Q] FOREIGN KEY([IDQuyen])
REFERENCES [dbo].[QUYEN] ([IDQuyen])
GO
ALTER TABLE [dbo].[TAIKHOAN] CHECK CONSTRAINT [FK_TK_Q]
GO
ALTER TABLE [dbo].[THANHTOAN]  WITH CHECK ADD  CONSTRAINT [FK_TT_DV] FOREIGN KEY([IDDV])
REFERENCES [dbo].[DICHVU] ([IDDV])
GO
ALTER TABLE [dbo].[THANHTOAN] CHECK CONSTRAINT [FK_TT_DV]
GO
ALTER TABLE [dbo].[THANHTOAN]  WITH CHECK ADD  CONSTRAINT [FK_TT_TK] FOREIGN KEY([IDTK])
REFERENCES [dbo].[TAIKHOAN] ([IDTK])
GO
ALTER TABLE [dbo].[THANHTOAN] CHECK CONSTRAINT [FK_TT_TK]
GO
ALTER TABLE [dbo].[VIDEO]  WITH CHECK ADD  CONSTRAINT [FK_VD_TL] FOREIGN KEY([IDTL])
REFERENCES [dbo].[THELOAI] ([IDTL])
GO
ALTER TABLE [dbo].[VIDEO] CHECK CONSTRAINT [FK_VD_TL]
GO
ALTER TABLE [dbo].[YEUTHICH]  WITH CHECK ADD  CONSTRAINT [FK_YEUTHICH_VIDEO] FOREIGN KEY([IDVideo], [LinkVideo])
REFERENCES [dbo].[VIDEO] ([IDVideo], [LinkVideo])
GO
ALTER TABLE [dbo].[YEUTHICH] CHECK CONSTRAINT [FK_YEUTHICH_VIDEO]
GO
ALTER TABLE [dbo].[YEUTHICH]  WITH CHECK ADD  CONSTRAINT [FK_YT_TK] FOREIGN KEY([IDTK])
REFERENCES [dbo].[TAIKHOAN] ([IDTK])
GO
ALTER TABLE [dbo].[YEUTHICH] CHECK CONSTRAINT [FK_YT_TK]
GO
USE [master]
GO
ALTER DATABASE [QuanLyCungCapVideo] SET  READ_WRITE 
GO
