//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCungCapVideo.Model
{
    using QuanLyCungCapVideo.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.YEUTHICHes = new HashSet<YEUTHICH>();
        }

        public int IDTK { get; set; }

        string _TenND;
        public string TenND { get => _TenND; set { _TenND = value; OnPropertyChanged(); } }

        string _MatKhau;
        public string MatKhau { get => _MatKhau; set { _MatKhau = value; OnPropertyChanged(); } }

        string _DienThoai;
        public string DienThoai { get => _DienThoai; set { _DienThoai = value; OnPropertyChanged(); } }

        string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }

        string _IDQuyen;
        public string IDQuyen { get => _IDQuyen; set { _IDQuyen = value; OnPropertyChanged(); } }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUTHICH> YEUTHICHes { get; set; }
    }
}
