//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCungCapVideo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public int IDThanhToan { get; set; }
        public string HTTT { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string GoiCuoc { get; set; }
        public string TenND { get; set; }
    }
}
