//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCungCapVideo.Model
{
    using QuanLyCungCapVideo.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN : BaseViewModel
    {
        public int IDTK { get; set; }

        private string _TenND;
        public string TenND { get => _TenND; set { _TenND = value; NotifyPropertyChanged("TenND"); } }

        private string _MatKhau;
        public string MatKhau { get => _MatKhau; set { _MatKhau = value; NotifyPropertyChanged("MatKhau"); } }

        private string _DienThoai;
        public string DienThoai { get => _DienThoai; set { _DienThoai = value; NotifyPropertyChanged("DienThoai"); } }

        private string _Email;
        public string Email { get => _Email; set { _Email = value; NotifyPropertyChanged("Email"); } }

        string _IDQuyen;
        public string IDQuyen { get => _IDQuyen; set { _IDQuyen = value; NotifyPropertyChanged("IDQuyen"); } }
    }
}
