//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCungCapVideo.Model
{
    using QuanLyCungCapVideo.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class YEUTHICH : BaseViewModel
    {
        public int IDYT { get; set; }

        string _TenND;
        public string TenND { get => _TenND; set { _TenND = value; NotifyPropertyChanged("TenND"); } }

        string _TenVideo;
        public string TenVideo { get => _TenVideo; set { _TenVideo = value; NotifyPropertyChanged("TenVideo"); } }

        string _QuocGia;
        public string QuocGia { get => _QuocGia; set { _QuocGia = value; NotifyPropertyChanged("QuocGia"); } }

        string _DaoDien;
        public string DaoDien { get => _DaoDien; set { _DaoDien = value; NotifyPropertyChanged("DaoDien"); } }

        string _TomTat;
        public string TomTat { get => _TomTat; set { _TomTat = value; NotifyPropertyChanged("TomTat"); } }

        int _LuotXem;
        public int LuotXem { get => _LuotXem; set { _LuotXem = value; NotifyPropertyChanged("LuotXem"); } }

        string _LinkVideo;
        public string LinkVideo { get => _LinkVideo; set { _LinkVideo = value; NotifyPropertyChanged("LinkVideo"); } }

        string _LinkPoster;
        public string LinkPoster { get => _LinkPoster; set { _LinkPoster = value; NotifyPropertyChanged("LinkPoster"); } }
    }
}
